export const SET_CURRENT_RENTAL = "SET_CURRENT_RENTAL";
export const GET_CURRENT_RENTAL = "GET_CURRENT_RENTAL";

export const SET_RENTAL_TO_ADD = "SET_RENTAL_TO_ADD";
export const GET_RENTAL_TO_ADD = "GET_RENTAL_TO_ADD";

export const FIND_BY_TITLE = "FIND_BY_TITLE";
export const FIND_BY_TITLE_SUCCESSFUL = "FIND_BY_TITLE_SUCCESSFUL";

export const SET_SEARCH_TITLE = "SET_SEARCH_TITLE";
export const GET_SEARCH_TITLE = "GET_SEARCH_TITLE";

export const SET_MESSAGE = "SET_MESSAGE";
export const GET_MESSAGE = "GET_MESSAGE";

export const SET_SUBMITTED = "SET_SUBMITTED";
export const GET_SUBMITTED = "GET_SUBMITTED";

export const SET_CURRENT_INDEX = "SET_CURRENT_INDEX";
export const GET_CURRENT_INDEX = "GET_CURRENT_INDEX";

export const GET_RENTALS = "GET_RENTALS";
export const GET_RENTALS_SUCCESSFUL = "GET_RENTALS_SUCCESSFUL";
export const SET_RENTALS = "SET_RENTALS";

export const GET_RENTAL = "GET_RENTAL";

export const ADD_RENTAL = "ADD_RENTAL";
export const ADD_RENTAL_SUCCESSFUL = "ADD_RENTAL_SUCCESSFUL";

export const UPDATE_RENTAL = "UPDATE_RENTAL";
export const UPDATE_RENTAL_SUCCESSFUL = "UPDATE_RENTAL_SUCCESSFUL";

export const DELETE_RENTAL = "DELETE_RENTAL";
export const DELETE_RENTAL_SUCCESSFUL = "DELETE_RENTAL_SUCCESSFUL";

export const DELETE_RENTALS = "DELETE_RENTALS";
export const DELETE_RENTALS_SUCCESSFUL = "DELETE_RENTALS_SUCCESSFUL";

// export const DATA_LOADED = "DATA_LOADED";
export const API_ERRORED = "API_ERRORED";

export const IS_FETCHING = "IS_FETCHING";
export const IS_UPDATING = "IS_UPDATING";
export const IS_DELETING = "IS_DELETING";
export const IS_DELETING_ALL = "IS_DELETING_ALL";
export const IS_ADDING = "IS_ADDING";
export const IS_FINDING = "IS_FINDING";


export const CREATE_GENERAL_MESSAGE = "CREATE_GENERAL_MESSAGE";
export const CREATE_GENERAL_MESSAGE_SUCCESSFUL = "CREATE_GENERAL_MESSAGE_SUCCESSFUL";

export const GET_MESSAGES = "GET_MESSAGES";
export const GET_MESSAGES_SUCCESSFUL = "GET_MESSAGES_SUCCESSFUL";

export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const DELETE_MESSAGE_SUCCESSFUL = "DELETE_MESSAGE_SUCCESSFUL";
